//CAMPAIGN types
export const CAMPAIGN_DETAILS_START = 'CAMPAIGN_DETAILS_START';
export const CAMPAIGN_DETAILS_SUCCESS = 'CAMPAIGN_DETAILS_SUCCESS';
export const CAMPAIGN_DETAILS_FAILURE = 'CAMPAIGN_DETAILS_FAILURE';

